## DO NOT TOUCH THIS FILE
# copy example.mk to local.mk and change that

# load defaults
include example.mk

# load customizations if exist
-include local.mk


VPATH=$(TOPDIR)
include $(TOPDIR)/module.mk
